### ISSUE TITLE
Não consegui usar o tagger

### ISSUE THREAD

**Issue by Daanielvb** [fmaruki/Nltk-Tagger-Portuguese#4]
Tentei utilizar o seu tagger mas não consegui. Você poderia deixar detalhado o processo de geração do pickle? Com qual versão do Python o mesmo é compatível? 

Tentei baixar os arquivos e tentar carregar o pickle, mas recebi o erro abaixo:

```
 tagger = pickle.load(open("../../data/tagger.pkl", 'rb'))
 print (tagger)
```

> 
>   File "~/text-extractor/src/util/Main.py", line 21, in <module>
>     tagger = pickle.load(open("../../data/tagger.pkl", 'rb'))
> ModuleNotFoundError: No module named 'copy_reg\r'
>

**Comment by fmaruki** [comment]
Não lembro mais que versão utilizava na época.
Mais tarde vou tentar carregar o arquivo novamente para ver se caio em
algum erro.

Enquanto isso, dê uma olhada nesta thread
https://stackoverflow.com/questions/556269/importerror-no-module-named-copy-reg-pickle/53942341#53942341

Cada resposta sugere uma solução completamente diferente hehe, talvez
alguma funcione com você.

**Comment by Daanielvb** [comment]
@fmaruki Tentei seguir as sugestões da thread mas nada pareceu funcionar. eu estou tentando abrir o pickle usando um win7, em qual SO vc gerou ele?

**Comment by fmaruki** [comment]
Em Linux, e a versão do Python é 3.*

Carreguei em uma máquina diferente da que foi gerada, em outra distribuição
e outra versão do Python, e foi sem problemas. Não tenho Windows para
testar se daria algum problema.

E quanto à treinar o modelo novamente e gerar um novo tagger, isto funciona
no seu ambiente? Pode demorar um pouco, mas as vezes isto pode sair mais
rapido do que arrumar o problema atual.

**Comment by Daanielvb** [comment]
@fmaruki acabei fazendo isso. Acho que quando o modelo é gerado num OS não linux acaba que não dá pra importar ele num windows. Criei meu próprio modelo e estou conseguindo usá-lo. De toda forma, obrigado pela ajuda.

**Comment by vschmidt** [comment]
Eu estava com o mesmo problema (usando o windows), bastou gerar o arquivo pickle novamente e usar sem problemas. Meus parabéns pela implementação, deu uma boa ajuda.
